In [24]:
import sys
import importlib
importlib.reload(sys)
sys.path.insert(0,'../')
import numpy as np
import netket as nk
from scripts import functions as f
from scripts import new_dynamics, new_dynamics2
import os
currentpath = os.getcwd()
parentdir = os.path.dirname(currentpath)

In [25]:
length=[4, 4]
V = 1.0
h = 1.0
g = nk.graph.Graph(nodes = [i for i in range(length[0] * length[1] * 2)])
hi = nk.hilbert.Spin(s=0.5, graph=g)


ham = f.dimer_hamiltonian(V = V, h = h ,length=np.array(length))
op_transition1 = f.dimer_flip1(length = np.array(length))


hex_ = nk.machine.new_hex(np.array(length))

ma = nk.machine.RbmDimer(hi, hex_, alpha = 2, symmetry = True
                    ,use_hidden_bias = False, use_visible_bias = False, dtype=float, reverse=True, half=True)
ma.init_random_parameters(seed=1234)

2


In [26]:
ma._ws[:] = 0

In [27]:
ma._set_bare_parameters(
    ma._a, ma._b, ma._w, ma._as, ma._bs, ma._ws, ma._autom, ma._z2
)

In [28]:
# N = 1000000
# temp = np.random.choice([-1,1],hex_.size*N).reshape(N, hex_.size)
# ind = hex_.is_dimer_basis(temp)

In [29]:

n_jobs = 12

g = nk.graph.Graph(nodes = [i for i in range(length[0] * length[1] * 2)])
hi = nk.hilbert.Spin(s=0.5, graph=g)

op = f.dimer_hamiltonian(h, V,np.array(length))
op_transition = f.dimer_flip1(length = np.array(length))
hex_ = nk.machine.new_hex(np.array(length))




sweep_size = 1000
sa_mul = nk.sampler.DimerMetropolisLocal_multi(machine=ma, op=op_transition, length = length, n_chains=1, sweep_size = sweep_size, kernel = 1, n_jobs=n_jobs)
sa_mul.reset()
_ = sa_mul.generate_samples(1000) # discard the begginings of metropolis sampling.
del _


number of core : 12


In [30]:
n_samples_ = 12
samples_state = sa_mul.generate_samples(int(n_samples_ / 1))
samples_state = samples_state.reshape(-1, ma.hilbert.size)
print('get samples')

get samples


In [43]:
import scripts.dynamics as Dynamics
importlib.reload(Dynamics)

<module 'scripts.dynamics' from '../scripts/dynamics.py'>

In [44]:
d = Dynamics.new_dynamics3(op, ma)

In [58]:
t_list = np.linspace(0,20,200)
p = d.dynamics(samples_state, t_list)

[ 0  1  5  6  7  8 10 11] [1 2 0 0 0 2 1 2 4 0 4 4]
[ 0  1  2  3  4  5  6  8  9 10 11] [5 3 1 2 1 5 2 2 5 1 5 5]
[ 0  1  2  3  4  5  6  8  9 11] [13  4  2  7  4  9  3  2  7  2  5 16]
[ 3  4  5  6  7  8  9 11] [13  4  2  9  9 10  4  5  9  4  5 21]
[ 1  2  3  5  6  8  9 10 11] [13  7  3 13  9 13  6  5 15  5  7 24]
[ 0  1  2  3  4  5  7  9 10 11] [14 19  8 14 10 15  6  7 15  6  8 25]
[ 0  1  2  3  4  6  8  9 10 11] [15 20 11 17 12 15  7  7 16  7  9 28]
[ 0  2  3  4  5  6  7  8  9 11] [27 20 12 18 15 16 10  9 17  8  9 29]
[ 0  1  2  3  4  6  7  8 10 11] [28 21 13 20 20 16 12 10 18  8 10 30]
[ 0  1  2  4  5  6  7  8  9 10] [31 22 14 20 21 18 17 12 19 11 14 30]
[ 0  2  3  4  7  8  9 10 11] [34 22 15 21 22 18 17 13 22 12 15 31]
[ 0  1  3  4  5  8  9 10] [35 24 15 22 23 26 17 13 24 18 17 31]
[ 2  4  5  6  7  8  9 10 11] [35 24 16 22 25 28 19 15 25 20 19 33]
[ 0  1  2  3  4  6  9 10 11] [38 28 18 25 26 28 26 15 25 22 21 34]
[ 0  1  2  3  4  5  6  7  8  9 11] [40 31 24 26 27 32 28 16 26 24 21 36

In [61]:
f.process_P2(p)

In [63]:
p[:,0,0]

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int8)

In [36]:
pp.shape

(100, 12, 32)

In [23]:
p[:,7,0]

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1,  1, -1,  1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,
        1,  1, -1,  1,  1, -1,  1, -1,  1,  1, -1, -1,  1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0,  0,  0,  0],
      dtype=int8)

In [10]:

P = P_[0]
T = P_[1]

# t_list = np.linspace(0,50,100)
t_list = np.arange(0,20,0.1)
P_list = f.process_P(P, T, t_list)

In [11]:
edge_coors = np.array([[ 0.5     ,  0.      ],
                       [ 0.25    , -0.433013],
                       [ 0.75    , -0.433013]])

a = np.tan((1/6)*np.pi) * 1/2
edge_coors_prime = np.array([
    hex_.a((1/2)*np.pi) * a,
    hex_.a(np.pi*(2/3)+(1/2)*np.pi) * a,
    hex_.a(np.pi*(4/3)+(1/2)*np.pi) * a,
])
edge_coors_prime = np.round(edge_coors_prime,10)

In [12]:
base_edge

NameError: name 'base_edge' is not defined

In [13]:
g = nk.graph.Graph(nodes = [i for i in range(length[0] * length[1] * 2)])
hi = nk.hilbert.Spin(s=0.5, graph=g)
hex_ = nk.machine.new_hex(np.array(length))


base_edge = edge_coors[1]
x = np.arange(length[0]*2)
y = np.arange(length[1]*2)

xx, yy = np.meshgrid(x,y)
xx = xx.reshape(-1)
yy = yy.reshape(-1)
edge_coor_array = hex_.ProcessPeriodic(xx[:,None] * hex_.a1[None,:] * 1/2 + yy[:,None]  * hex_.a2[None,:] * 1/2 + base_edge)
edges = hex_.edge_coor_to_lattice(edge_coor_array)
colors = hex_.get_edge_color(edges)

operators = f.return_spin_corr(hi, edges, colors)

In [14]:
edges

array([[ 8, 15],
       [ 8, 12],
       [ 9, 12],
       [ 9, 13],
       [10, 13],
       [10, 14],
       [11, 14],
       [11, 15],
       [-1, -1],
       [12, 16],
       [-1, -1],
       [13, 17],
       [-1, -1],
       [14, 18],
       [-1, -1],
       [15, 19],
       [16, 23],
       [16, 20],
       [17, 20],
       [17, 21],
       [18, 21],
       [18, 22],
       [19, 22],
       [19, 23],
       [-1, -1],
       [20, 24],
       [-1, -1],
       [21, 25],
       [-1, -1],
       [22, 26],
       [-1, -1],
       [23, 27],
       [24, 31],
       [24, 28],
       [25, 28],
       [25, 29],
       [26, 29],
       [26, 30],
       [27, 30],
       [27, 31],
       [-1, -1],
       [ 0, 28],
       [-1, -1],
       [ 1, 29],
       [-1, -1],
       [ 2, 30],
       [-1, -1],
       [ 3, 31],
       [ 0,  7],
       [ 0,  4],
       [ 1,  4],
       [ 1,  5],
       [ 2,  5],
       [ 2,  6],
       [ 3,  6],
       [ 3,  7],
       [-1, -1],
       [ 4,  8],
       [-1, -1

In [52]:
K = np.zeros((2*length[0],2*length[1],2))
for l1 in range(K.shape[0]):
    for l2 in range(K.shape[1]):
        K[l1,l2] = hex_.b1 * 2*np.pi*l1/K.shape[0] + hex_.b2 * 2*np.pi*l2/K.shape[1]

In [53]:
K.shape

(8, 8, 2)

In [54]:
edge_coors_prime[0]

array([0.        , 0.28867513])

In [55]:
uni = np.exp(1j*np.einsum('ijk,lk->lij',K,edge_coors_prime))

In [56]:
num_samples = (P_list[:,:,0]!=0).sum(axis=1)
P_list_ = P_list.reshape(-1,P_list.shape[-1])
sections1 = np.arange(P_list.shape[1])
sections2 = np.zeros(P_list_.shape[0])

_, mels1 = operators[0].get_conn_flattened(P_list[0,:,:], sections1)
sub1 = mels1.mean().real
mels1 = mels1.real


dimer_corr = np.zeros((2*length[0],2*length[1],t_list.shape[0]))
dimer_std = np.zeros((2*length[0],2*length[1],t_list.shape[0]))


for l2 in range(2*length[1]):
    for l1 in range(2*length[0]):
#     l1 = 1
#     l2 = 0
        print(l1,l2)
        if operators[l1 + l2 * 2*length[0]]:
            sub2 = operators[l1 + l2 * 2*length[0]].get_conn_flattened(P_list[0,:,:], sections1)[1].mean().real
            print(sub2)
            _, mels2_ = operators[l1 + l2 * 2*length[0]].get_conn_flattened(P_list_, sections2)
            mels2 = mels2_.reshape(P_list.shape[0], P_list.shape[1]).real
            dimer_corr[l1,l2] = (mels2 * mels1).sum(axis=1)/num_samples 
            dimer_std[l1,l2] = (mels2 * mels1).std(axis=1)
        else:
            dimer_corr[l1,l2] = 0
            dimer_std[l1,l2] = 0

0 0
-0.6687469995199231
1 0
-0.6663066090574492
2 0
-0.6711473835813729
3 0
-0.6610657705232837
4 0
-0.6715474475916147
5 0
-0.6598655784925588
6 0
-0.6677868458953432
7 0
-0.6630260841734678
0 1
1 1
-0.6636661865898543
2 1
3 1
-0.6727076332213153
4 1
5 1
-0.6636661865898543
6 1
7 1
-0.6679468714994399
0 2
-0.6685069611137782
1 2
-0.6661465834533525
2 2
-0.6652664426308209
3 2
-0.6663466154584733
4 2
-0.6658665386461834
5 2
-0.6683869419107057
6 2
-0.6691870699311889
7 2
-0.6648263722195551
0 3
1 3
-0.6595055208833414
2 3
3 3
-0.6646263402144342
4 3
5 3
-0.66650664106257
6 3
7 3
-0.6764282285165626
0 4
-0.664546327412386
1 4
-0.6711873899823971
2 4
-0.6730676908305329
3 4
-0.6665466474635942
4 4
-0.6680668907025124
5 4
-0.6623059689550328
6 4
-0.6607457193150904
7 4
-0.6648663786205793
0 5
1 5
-0.6681869099055848
2 5
3 5
-0.6620659305488877
4 5
5 5
-0.6743078892622819
6 5
7 5
-0.6631861097775644
0 6
-0.6689870379260682
1 6
-0.6657065130420867
2 6
-0.6644263082093135
3 6
-0.667786845895

In [59]:
sub1 * 48 * (-2/3)

21.399903984637536

In [57]:
dimer_corr.sum(axis=(0,1))

array([21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39990398,
       21.39990398, 21.39990398, 21.39990398, 21.39990398, 21.39

In [33]:
-2/3 * 48

-32.0

In [71]:
tau_list = []
N = 2000
corr1 = []
corr2 = np.zeros((81,N),dtype=np.complex128)
n = -1
import re
with open('K4_4V1.0st.dat') as fe:
    for line in fe:
        
        if re.findall(r'#\d', line):
            i = 0
            n += 1
        else:
            try:
                match = re.findall(r'[\d,\.]+', line)
                tau_list.append(float(match[1]))
                corr1.append(float(match[2]))
                corr2[n,i] = float(match[2]) + 1j*float(match[3])
                i+=1
            except:
                pass
            

In [74]:
corr2[1]

array([0.02205296+0.01001865j, 0.01875094+0.01129549j,
       0.01601842+0.01156013j, ..., 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ])

In [68]:
fft_dimer_corr_prime - corr2[1]

array([[[ 6.41088174e+01+0.00000000e+00j,
          6.41088174e+01+0.00000000e+00j,
          6.41088174e+01+0.00000000e+00j, ...,
          6.41088174e+01+0.00000000e+00j,
          6.41088174e+01+0.00000000e+00j,
          6.41088174e+01+0.00000000e+00j],
        [ 8.10513451e-02+8.16017401e-02j,
          7.09706089e-02+6.75812434e-02j,
          5.71711079e-02+5.58663197e-02j, ...,
         -2.78779989e-04-6.12363881e-04j,
          9.84691330e-04-7.46648107e-04j,
          1.06420122e-03-6.65821767e-04j],
        [ 1.49657447e+00+4.01005927e-01j,
          1.34014673e+00+3.59091240e-01j,
          1.20976452e+00+3.24155432e-01j, ...,
         -3.86432159e-04-1.03544187e-04j,
          1.54572864e-03+4.14176748e-04j,
          1.77758793e-02+4.76303260e-03j],
        ...,
        [ 1.48309239e+00-1.09268509e-01j,
          1.23831994e+00-7.38834879e-02j,
          1.01975090e+00-6.75432109e-02j, ...,
         -1.02687688e-02+2.24319638e-03j,
         -9.05964646e-03+8.45728754e-03j

In [35]:
import pickle
with open('/home/keisuke/Documents/dimermaster/save/corr/h=1.0V=1.0l=[4, 4]/n=1.0e+05','rb') as fp:
    [fft_dimer_corr_prime, t_list, num_samples] = pickle.load(fp)

In [36]:
fft_dimer_corr_prime[0,0]

array([64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j, 64.10881741+0.j,
       64.10881741+0.j, 6

In [39]:
K = np.zeros((2*length[0],2*length[1]))
for l1 in range(K.shape[0]):
    for l2 in range(K.shape[1]):
        K[l1,l2] = 2*np.pi*l1/K.shape[0] + 2*np.pi*l2/K.shape[1]

In [41]:
U = np.exp(1j * K)

In [24]:
np.unravel_index(np.argmin(B),B.shape)

(7, 1)

In [147]:
np.unravel_index(np.argmin(A, axis=None), A.shape)

(7, 7)

In [152]:
np.where((corr2[1] - corr2[2]) != 0)

(array([ 696,  856, 1020]),)

In [145]:
dimer_corr[:,1,0]

array([0.33017283, 0.33421347, 0.45667307, 0.41334614, 0.41466635,
       0.45383261, 0.32621219, 0.3337734 ])

In [163]:
np.where(np.mean(corr2 - corr2[14],axis=1).round(5)==0)

(array([14, 22, 26, 31]),)

In [107]:
np.abs(dimer_corr[:,1] - corr2[4][:200]).mean(axis=1)

array([0.03491236, 0.44306074, 0.02083999, 0.44306074, 0.01132994,
       0.00236936, 0.00682221, 0.01105662])

In [16]:
corr2[5]

array([0.45833333, 0.45814134, 0.45771851, ..., 0.44444444, 0.44444444,
       0.44444444])

In [92]:
d = f._dynamics(
    op._local_states,
    op._basis,
    op._constant,
    op._diag_mels,
    op._n_conns,
    op._mels,
    op._x_prime,
    op._acting_on,
    op._acting_size
)

In [94]:
P = d.dynamics(samples_state.astype(np.int8), t_list, 0)

In [95]:
P_list = P.transpose(1,0,2)

In [52]:
t_list_ = t_list.reshape(-1,1)
n = 1
index = np.logical_and(T[n] <= t_list_,  t_list_ < T[n+10])

In [37]:
import scipy.fft as fft
fft_dimer_corr = np.empty_like(dimer_corr)
for t in range(t_list.shape[0]):
    fft_dimer_corr[:,:,t] = np.real(fft.fft2(dimer_corr[:,:,t]))

In [47]:
-2/3 * 48 * (-2/3)

21.333333333333332

In [45]:
dimer_corr[:,:,1].sum()

21.426788286125777

In [38]:
fft_dimer_corr[0,0]

array([21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42678829,
       21.42678829, 21.42678829, 21.42678829, 21.42678829, 21.42

In [84]:
from plotly import graph_objects as go


In [86]:
fig = go.Figure()
fig.add_trace(
    go.Scatter(
        x = t_list,
        y = dimer_corr[0, 0],
    )
)

fig.add_trace(
    go.Scatter(
        x = tau_list,
        y = corr2,
    )
)
fig.show()